version: '3.4'

services:
  client:
    image: client
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200
    volumes: 
      - .:/usr/src/app
